on: [push, pull_request]

name: Build (Linux/macOS/Windows)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Smoketest (Windows) - quick exit (here-string)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          @"
      0
      "@ | .\build\Release\ecommerce.exe
        continue-on-error: true

      # Run the Linux/macOS smoketest
      - name: Smoketest (Linux / macOS)
        if: runner.os != 'Windows'
        run: ./build/ecommerce
        shell: bash
        continue-on-error: true
